CREATE TABLE IF NOT EXISTS canvases (
    id UUID PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    viewport_x DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    viewport_y DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    zoom_level DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
